name: CI/CD for AKS Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.9

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan

    - name: Terraform Apply
      run: terraform apply -input=false tfplan
      env:
        ARM_CLIENT_ID: 3d8063b3-3657-4a03-8fe5-ab9fc694c9f3
        ARM_CLIENT_SECRET: IF58Q~TEHCrN55sCYzBMrFIM1JluGC08JrJgVbd0
        ARM_SUBSCRIPTION_ID: 6f9a1c1c-f8a5-4e98-bd17-18dd4194267a
        ARM_TENANT_ID: 1dace772-cc35-4790-866d-b7a4cf63ab3a

    - name: AKS Kubeconfig
      run: |
        az aks get-credentials --resource-group myResourceGroup --name myakscluster
        kubectl config use-context myakscluster

    - name: Deploy API
      run: kubectl apply -f api-deployment.yaml
